<#
.SYNOPSIS
  Builds the firmware with PlatformIO and puts the file to upload through the
  web UI in ..\build (a "build" folder next to the sketch folder).

.DESCRIPTION
  Compiles platformio.ini's firebeetle2_c6 environment (FireBeetle 2
  ESP32-C6, Zigbee + Wi-Fi, light sleep) and copies its application image to
  the output folder as velux_wli_130_51_c6.bin. Nothing else is written there.
  WebUI_gz.h is regenerated by the build itself (tools/pio_prebuild.py).
  With -Upload it also flashes the board over USB.

  Uses pio from PATH, or else the copy the VS Code "PlatformIO IDE" extension
  installs in %USERPROFILE%\.platformio\penv. The first build recompiles
  ESP-IDF (20-30 minutes); later ones only recompile what changed.

.PARAMETER OutDir
  Output folder. Default: ..\build relative to this script.

.PARAMETER Jobs
  Parallel compile jobs. Default: PLATFORMIO_RUN_JOBS if set (VS Code sets it
  in .vscode/settings.json), else one per logical CPU. More than that doesn't
  help: the compile already keeps every CPU at 100%.

.PARAMETER Upload
  Also flash the board over USB (pio's "upload" target) - needed for the
  first flash, which writes the partition table too.

.PARAMETER Port
  Serial port for -Upload, e.g. COM4. Default: PlatformIO picks it.

.EXAMPLE
  .\export_release.ps1
.EXAMPLE
  .\export_release.ps1 -Upload -Port COM4
#>
param(
  [string]$OutDir = '',
  [int]$Jobs = 0,
  [switch]$Upload,
  [string]$Port = ''
)

$ErrorActionPreference = 'Stop'
$root = $PSScriptRoot
$sketchName = 'velux_wli_130_51'
$pioEnv = 'firebeetle2_c6'

if (-not $OutDir) { $OutDir = Join-Path $root '..\build' }
New-Item -ItemType Directory -Force -Path $OutDir | Out-Null
$OutDir = (Resolve-Path $OutDir).Path
# "_c6": the master branch's ESP32 build lands in the same folder as
# velux_wli_130_51.bin - the two must never be mixed up on upload.
$binName = "${sketchName}_c6.bin"
$outPath = Join-Path $OutDir $binName

# kVersion straight out of src/Config.h, only to report which firmware the .bin
# contains (the board shows the same string under Advanced -> Device).
$match = Select-String -Path (Join-Path $root 'src/Config.h') -Pattern 'kVersion\s*=\s*"([^"]+)"' | Select-Object -First 1
if (-not $match) { Write-Error "Could not find kVersion in src/Config.h - is this script in the project folder?" }
$version = $match.Matches[0].Groups[1].Value

if ($Jobs -le 0) {
  $fromEnv = 0
  if ([int]::TryParse("$env:PLATFORMIO_RUN_JOBS", [ref]$fromEnv) -and $fromEnv -gt 0) {
    $Jobs = $fromEnv
  } else {
    $Jobs = [Environment]::ProcessorCount
  }
}
# The hybrid build compiles ESP-IDF, then starts a second "pio run" without
# --jobs for the Arduino part: that one only sees this.
$env:PLATFORMIO_RUN_JOBS = "$Jobs"
# ESP-IDF's tools refuse to run when they see a Git Bash / MSYS environment
# ("MSys/Mingw is not supported"); this script may have been started from one.
Remove-Item Env:MSYSTEM -ErrorAction SilentlyContinue

$pioCmd = Get-Command pio -ErrorAction SilentlyContinue
$pioPath = if ($pioCmd) { $pioCmd.Source } else { Join-Path $env:USERPROFILE '.platformio\penv\Scripts\pio.exe' }
if (-not (Test-Path $pioPath)) {
  Write-Error "PlatformIO not found (neither on PATH nor in $env:USERPROFILE\.platformio\penv). Install the 'PlatformIO IDE' extension in VS Code and let it finish setting up, then run this again."
}

$pioArgs = @('run', '--project-dir', $root, '--environment', $pioEnv, '--jobs', $Jobs)
if ($Upload) {
  $pioArgs += @('--target', 'upload')
  if ($Port) { $pioArgs += @('--upload-port', $Port) }
}

Write-Output "Building with $pioPath ($Jobs parallel jobs)$(if ($Upload) { ', then flashing over USB' })..."
# PlatformIO prints warnings on stderr; with $ErrorActionPreference = 'Stop'
# Windows PowerShell 5.1 turns those into terminating errors whenever the
# output is redirected. Only the exit code decides here.
$ErrorActionPreference = 'Continue'
& $pioPath @pioArgs
$exit = $LASTEXITCODE
$ErrorActionPreference = 'Stop'
if ($exit -ne 0) {
  $hint = if ($Upload) { ' If the port is busy, close the serial monitor first.' } else { '' }
  Write-Error "PlatformIO $(if ($Upload) { 'build/upload' } else { 'build' }) failed (exit $exit).$hint"
}

$source = Join-Path $root ".pio\build\$pioEnv\firmware.bin"
if (-not (Test-Path $source)) { Write-Error "The build finished but produced no $source." }
Copy-Item -Path $source -Destination $outPath -Force

Write-Output ""
Write-Output "Version: $version"
Write-Output ("Output : {0}  ({1:N0} bytes)" -f $outPath, (Get-Item $outPath).Length)
Write-Output ""
if ($Upload) {
  # The reset over the chip's own USB port doesn't always get through.
  Write-Output "Flashed over USB. If the board doesn't restart on its own, press RST."
  Write-Output "Next updates: $binName through the board's web UI (switch ON)."
} else {
  Write-Output "Upload $binName through the board's web UI: switch ON, Advanced tab -> Firmware update."
}
