// Regenerates WebUI_gz.h - the gzipped copy of the web page that the firmware
// actually serves - from the page source in WebUI.h.
//
// Run it after EVERY edit of src/WebUI.h, from the project folder:
//
//     node tools/build_webui_gz.js
//
// Needs only Node.js (no npm packages). The firmware checks at compile time
// that WebUI_gz.h matches WebUI.h (webUiHash() in main.cpp) and refuses to
// build if you forget, so a stale page can never be flashed by accident.

const fs = require('fs');
const path = require('path');
const zlib = require('zlib');

const root = path.join(__dirname, '..', 'src');
const srcPath = path.join(root, 'WebUI.h');
const outPath = path.join(root, 'WebUI_gz.h');

const src = fs.readFileSync(srcPath, 'utf8');
const open = 'R"PAGE(', close = ')PAGE"';
const a = src.indexOf(open), b = src.indexOf(close);
if (a < 0 || b < a) {
  console.error('WebUI.h: page markers R"PAGE( ... )PAGE" not found');
  process.exit(1);
}

// Exactly the bytes between the markers, as the compiler sees them. '\r' is
// dropped on both sides (here and in webUiHash()) so a CRLF checkout of
// WebUI.h hashes the same as an LF one.
const page = Buffer.from(src.slice(a + open.length, b).replace(/\r/g, ''), 'utf8');

// FNV-1a, 32 bit - must match webUiHash() in main.cpp.
let h = 2166136261;
for (const byte of page) {
  h ^= byte;
  h = Math.imul(h, 16777619) >>> 0;
}

const gz = zlib.gzipSync(page, { level: 9 });
gz[9] = 0xff;   // header "OS" byte: fixed, so every machine produces identical output

const lines = [];
for (let i = 0; i < gz.length; i += 16) {
  lines.push('  ' + Array.from(gz.subarray(i, i + 16), (x) => '0x' + x.toString(16).padStart(2, '0')).join(','));
}

const out = `// GENERATED by tools/build_webui_gz.js from src/WebUI.h - do not edit by hand.
// After changing WebUI.h run:  node tools/build_webui_gz.js
#pragma once
#include <stdint.h>

// Page source: ${page.length} bytes -> gzip: ${gz.length} bytes.
static constexpr uint32_t kIndexHtmlGzSourceHash = 0x${h.toString(16).padStart(8, '0')}u;

static const uint8_t kIndexHtmlGz[] = {
${lines.join(',\n')}
};
`;

fs.writeFileSync(outPath, out);
console.log(`WebUI_gz.h: ${page.length} -> ${gz.length} bytes (${Math.round(100 * gz.length / page.length)}%), hash 0x${h.toString(16).padStart(8, '0')}`);
